# -*- mode: sh -*-

# general settings
shopt -s checkwinsize    # Handle window resize
shopt -s extglob         # enable extra glob patterns
set -o notify
set -o physical

# Work out where we are
LHOST=$(uname -n)
SHOST=${LHOST%%.*}
OSNAME=$(uname -s)
OSKERNEL=$(uname -r)
export LHOST SHOST OSNAME OSKERNEL

# Editor and Pager
EDITOR=vi
PAGER="less -FRXi"
MANPAGER="less -FRXi"
LESS="-FRXi"
export EDITOR PAGER MANPAGER LESS 

# Prompt
# git status, short host name, last 20 characters of PWD
export NO_PROMPT_VARS
PS1SHOST=$SHOST
case $OSNAME in
    Linux)
        if [ -d /etc/bash_completion.d/git-prompt ]; then
            . /etc/bash_completion.d/git-prompt
        fi
        ;;
    Darwin)
        if [ -d $(brew --prefix)/etc/bash_completion.d ]; then
            . $(brew --prefix)/etc/bash_completion.d/git-prompt.sh
        fi
        ;;
esac

GIT_PS1_SHOWCOLORHINTS=true
GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWSTASHSTATE=true
GIT_PS1_SHOWUNTRACKEDFILES=
GIT_PS1_SHOWUPSTREAM=

COLOR_OFF='\e[0m'
GOLD='\e[38;5;220m'

# __git_ps1 takes up to three arguments:
# $1 before git status (empty)
# $2 after git status
# $3 format string for git status
PROMPT_COMMAND='__git_ps1 \
  "" \
  "\[$GOLD\]\h\[$COLOR_OFF\]:`echo $PWD | tail -20c`: "\
  "[%s]" \
  '

# Add an element to the end of an environment variable
addenv () {
    eval ${1}=$(echo $(eval echo "$\{$1\}")):"$2"
    export ${1}
}

# Build path from scratch
unset PATH
PATH=/sbin # Set first path element directly to avoid leading ':' in the path
addenv PATH /bin
addenv PATH /usr/sbin
addenv PATH /usr/bin
addenv PATH ~/tools/bin
addenv PATH /usr/local/sbin
addenv PATH /usr/local/bin
addenv PATH /usr/local/go/bin

# Build manpath
unset MANPATH
addenv MANPATH /usr/share/man
addenv MANPATH ~/tools/man
addenv MANPATH /usr/local/man

# Go
export GOPATH=~/src/go
addenv PATH $GOPATH/bin

# OPAM configuration
. ~/.docker-ci-cache/opam/opam-init/init.sh > /dev/null 2> /dev/null || true

# History
command_oriented_history=TRUE
shopt -s histappend
export HISTIGNORE="&:l[sl][a]:[bf]g:exit:[ \t]"
export HISTCONTROL=ignoreboth:erasedups
export HISTSIZE=10000
export HISTFILESIZE=10000

# Aliases
alias ls='ls -F'
alias ll='ls -l'
alias la='ls -al'
alias lm='ls -al | less'

alias grep='grep --color=auto '

alias psg='ps -auwx | grep \!* | grep -v grep'

case $OSNAME in
    Linux)
        # copy working directory
        alias cwd='pwd | tr -d "\r\n" | xclip -selection clipboard'
        ;;
    Darwin)
        # copy working directory
        alias cwd='pwd | tr -d "\r\n" | pbcopy'
        # prefer brew version of git
        [ -e /usr/local/bin/git ] && alias git=/usr/local/bin/git
        # Use emacs app
        alias emacs=/Applications/Emacs.app/Contents/MacOS/Emacs
        ;;
esac

# include aliases and functions
[ -r ~/.bash_fns ] && source ~/.bash_fns

# Brew bash completions on MacOS
if [ $OSNAME = "Darwin" ]; then
    if [ -f $(brew --prefix)/etc/bash_completion ]; then
        . $(brew --prefix)/etc/bash_completion
    fi
fi
