syntax enable
set showmode
set showcmd
set wildmenu
set ruler<
set autoindent
set expandtab
set wrap
set hlsearch
set showmatch
set ignorecase
set smartcase
setlocal spell spelllang=en_gb
nnoremap _ :set invhlsearch<CR>
set tabstop=8
set shiftwidth=4
set shiftround