;;; geiser-kawa-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from geiser-kawa.el

(defconst geiser-kawa-elisp-dir (file-name-directory (or load-file-name (buffer-file-name))) "\
Directory containing geiser-kawa's Elisp files.")
(defconst geiser-kawa-dir (if (string-suffix-p "elisp/" geiser-kawa-elisp-dir) (expand-file-name "../" geiser-kawa-elisp-dir) geiser-kawa-elisp-dir) "\
geiser-kawa's directory.")
(autoload 'run-kawa "geiser-kawa" "\
Start a Geiser Kawa Scheme REPL." t)
(autoload 'switch-to-kawa "geiser-kawa" "\
Start a Geiser Kawa Scheme REPL, or switch to a running one." t)
(register-definition-prefixes "geiser-kawa" '("geiser-kawa-"))

;;; End of scraped data

(provide 'geiser-kawa-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; geiser-kawa-autoloads.el ends here
